language: ruby
branches:
  only:
    - master
install:
  - sudo apt-get install -y graphviz
  - bundle
env:
  global:
    - secure: "Bnm/Iq7UjATla4c0L6VlO9+iDY+hXzEwaBon61kV863DwGcoZDfOEiuS+AJ5SRiuj6dom2151xa0rHpE3W2fVl6zLae92OZv5sPouIRx98HVLEflu19RNXzjm9v+DbeEWpqRz8outfR4RcBye6jKLHU0zPish2ZTgPRDm9WWjL0="
script: jgd -u https://yegor256:$PASSWORD@github.com/yegor256/xdsd.git

