name: xdsd
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
permalink: pretty

# see https://github.com/noct/jekyll-sass
gems: ['jekyll-sass', 'jekyll/timeago']
sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: false

